# Generated by Django 5.2.3 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('user', 'Default User'), ('eleve', 'Eleve'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('superadmin', 'Superadmin')], default='user', max_length=20),
        ),
    ]
